server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: $LOKI_URL
    basic_auth:
      username: $LOKI_USER
      password: $LOKI_PASSWORD

scrape_configs:
  - job_name: app
    pipeline_stages:
      - template:
          source: stream
          template: '{{ .Labels.__stream__ }}'
          output: stream
      - labels:
          stream:
    static_configs:
      - targets:
          - localhost
        labels:
          job: backend
          __path__: /proc/1/fd/1
          __stream__: stdout
      - targets:
          - localhost
        labels:
          job: backend
          __path__: /proc/1/fd/2
          __stream__: stderr
      - targets:
          - localhost
        labels:
          job: backend
          __path__: /var/log/*log

