name: Backend CI

on:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Run tests
        run: pytest backend/tests
      - name: Build Docker image
        run: |
          docker build -t backend-image ./backend
          docker save backend-image | gzip > backend-image.tgz
      - name: Upload Docker artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-image
          path: backend-image.tgz
