# .github/workflows/ci-backend.yml

name: CI Backend

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - 'pyproject.toml'
  pull_request:
    paths:
      - 'backend/**'
      - 'pyproject.toml'

jobs:
  python-lint-test:
    name: Python Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest ruff black # Instala lo necesario para linting
      
      - name: Run Linters
        run: |
          ruff check .
          black --check .
      
      - name: Run tests
        run: pytest
